### ISSUE TITLE
stack services have been deployed in nodes not assigned to the simcore- stack

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-ops-environments#278]
Were: aws production

For instance
![image](https://github.com/ITISFoundation/osparc-ops-environments/assets/32402063/4ce12c33-2638-4754-a782-23c213775daa)

**Comment by YuryHrytsuk** [comment]
The changes in `osparc-simcore` repository can be found in the PR below. These changes are part of the new logic to ensure that simcore services are run on simcore nodes.  All the placement constraints will reside in `osparc-ops-environments` repository from now on.


https://github.com/ITISFoundation/osparc-simcore/pull/4571

**Comment by YuryHrytsuk** [comment]
The changes in `osparc-infra` repository can be found in the PR below. These changes introduce a new label for docker swarm nodes. This label will be used to place simcore services. This tag identifies so-called simcore nodes which run simcore services. This label is assigned no some nodes for every deployment.

https://git.speag.com/oSparc/osparc-infra/-/merge_requests/144

**Comment by YuryHrytsuk** [comment]
The changes in `osparc-ops-environments` repository can be found in the PR below. These changes introduce new docker placement constraints for simcore services which will be mostly run on simcore nodes (node with label `simcore == true`). There are exceptions since some simcore services have to be run on manager nodes.

https://github.com/ITISFoundation/osparc-ops-environments/pull/300

**Comment by YuryHrytsuk** [comment]
The PRs were merged in all 3 repositories. Simcore services will run on Simcore nodes from now on.
