### ISSUE TITLE
POC: Implement Simcore CI/CD via GitLab Pipelines

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#336]
Currently, we manually release new versions of osparc project. Some logic is automated by `deployment-agent`. We would like to fully automate the whole deployment process. As a first step, we should try GitLab Pipelines.

**Comment by YuryHrytsuk** [comment]
https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/48#f921a61f52a8f3377d6a0ddd8dbadb0899062ea3_5_0

**Comment by mrnicegyu11** [comment]
Ideas / second-iteration items to make the new awesome CI/CD robust:
- Use gitlab CI stages: `plan` creates docker-compose.yml, `apply` (triggered manually) applites changes. In the future we can add `test` before `plan`, where we check that env-vars are correct and migrations work successfully
- We need to keep in mind that we ideally want to also handle the existance / inventory of simcore-microservices' docker images on dockerhub. With this I mean that, we do not want to deploy (fail the pipeline or retry) of the docker images belonging to a git tag or not yet fully built or for any reason unavailable on dockerhub. Ideally, we always want to deploy strictly version-pinned docker images, so something like `itisfoundation/webserver:staging_Baklava2` instead of `itisfoundation/webserver:staging-github-latest`. The same goes for the env-var `DYNAMIC_SIDECAR_IMAGE=itisfoundation/dynamic-sidecar:release-github-latest
`, which should better be version pinned.

**Comment by YuryHrytsuk** [comment]
A new implementation with Ansible. This makes us independant from Portainer (API) and allows us to easily deploy all stacks (both OPS and Simcore):
https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/54

**Comment by mrnicegyu11** [comment]
done
