### ISSUE TITLE
Design flaw in ENV process

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-ops-environments#463]
Since OPS uses the latest version of the repo.config in osparc.io when it is deployed, we just cannot push a PR in simcore and modify all the repo.config files. Reason for this is what I failed to properly ask in our last meetings, how is it possible to change the repo.config of AWS-production when it will only be released in 2 months? conclusion is that we can change the repo.config of master right away (as it will obviously also be broken quite instantly after the PR is deployed), but the other repo.config files that is another story... No problem with new variables, but big CAUTION with modifications/deletion (C) @sanderegg 

@sanderegg @mrnicegyu11 @GitHK @pcrespov

**Comment by pcrespov** [comment]
@YuryHrytsuk As you mention at the end of the description, the only problem would arise with *modification* or *deletion* of env-vars.  

As a first step I would propose:
- protect `config` branch and only allow PRs with reviews
- Add a PR template with checks that warns about this
- *modifications* or *deletions* can be added as comments with a reference to release issue/name (not super happy about thisone since it would require an extra PR upon release)

**Comment by YuryHrytsuk** [comment]
The approach is to branch off (created by Matus)

**Comment by YuryHrytsuk** [comment]
Updated & Documented here: https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/298

**Comment by YuryHrytsuk** [comment]
with the help of @matusdrobuliak66 and @sanderegg
